# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1322, 885)
        MainWindow.setMinimumSize(QtCore.QSize(1135, 885))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(9)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("#bg {\n"
"    background-color: #E6E7F0;\n"
"}\n"
"\n"
"#topBar {\n"
"    background-color: #15161D;\n"
"\n"
"}\n"
"\n"
"QLabel {\n"
"color:white;\n"
"    font: 10pt \"Rubik\";\n"
"}\n"
"#mainTableFrame {\n"
"border:2px solid #BFC1D3;\n"
"border-radius:8px;\n"
"background-color:white;\n"
"}\n"
"\n"
"#mainBar {\n"
"background-image: url(:/icons/images/icons/bg.png);\n"
"    background-image: url(:/icons/images/icons/bg2.png);\n"
"}\n"
"#rightMainFrame{\n"
"border:2px solid #BFC1D3;\n"
"border-radius:8px;\n"
"background-color:white;\n"
"}\n"
"#lblStatusRec {\n"
"    max-width: 15px;\n"
"    max-height: 15px;\n"
"    border-radius: 7px; \n"
"    margin-right: 10px; \n"
"    background-color: #25993F;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*Combo Box */\n"
"QComboBox {\n"
"    border: none; /* Remove border */\n"
"    background-color: transparent; /* Make background transparent */\n"
"    font: 9pt \"Rubik\"; /* Set font to Rubik */\n"
"    padding: 2px 5px; /* Add padding (adjust as needed) */\n"
"    color: #4F5268; /* Text color */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #FFFFFF; /* Set the dropdown background color to white */\n"
"    border: 1px solid #D3D3D3; /* Light border for dropdown list */\n"
"    font: 9pt \"Rubik\"; /* Font for dropdown items */\n"
"    padding: 5px; /* Padding inside dropdown items */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none; /* Remove border from the drop-down button */\n"
"    background: transparent; /* Make the drop-down button background transparent */\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"  \n"
"    image: url(:/icons/images/icons/drop.png);\n"
"    width: 22px; /* Adjust width of arrow */\n"
"    height: 22px; /* Adjust height of arrow */\n"
"}\n"
"\n"
"QComboBox::item {\n"
"    padding: 5px 10px; /* Padding inside each item in the list */\n"
"    font: 9pt \"Rubik\"; /* Set font for items */\n"
"}\n"
"\n"
"QToolTip {\n"
"            background-color: #333; /* Dark background color */\n"
"            color: #fff;            /* White text color */\n"
"            border: 1px solid #666; /* Dark border color */\n"
"            padding: 5px;           /* Padding around the text */\n"
"        }\n"
"\n"
"\n"
"\n"
"/* Vertical ScrollBar */\n"
"QScrollArea {\n"
"    border: none;\n"
"    background-color: #FFFFFF; /* Set background to white */\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: 1px solid #D3D3D3; /* Light border color */\n"
"    background: #F9F9F9; /* Light background color */\n"
"    width: 12px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #B0B0B0; /* Dark grey color */\n"
"    min-height: 20px;\n"
"    border-radius: 5px; /* Rounded handle */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    background: #D3D3D3; /* Light border color */\n"
"    height: 12px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    background: #D3D3D3; /* Light border color */\n"
"    height: 12px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    border: 2px solid #B0B0B0; /* Dark grey color */\n"
"    width: 3px;\n"
"    height: 3px;\n"
"    background: #FFFFFF; /* White arrow background */\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* Horizontal ScrollBar */\n"
"QScrollBar:horizontal {\n"
"    border: 1px solid #D3D3D3; /* Light border color */\n"
"    background: #F9F9F9; /* Light background color */\n"
"    height: 12px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #B0B0B0; /* Dark grey color */\n"
"    min-width: 20px;\n"
"    border-radius: 5px; /* Rounded handle */\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    background: #D3D3D3; /* Light border color */\n"
"    width: 12px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: #D3D3D3; /* Light border color */\n"
"    width: 12px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::left-arrow:horizontal, QScrollBar::right-arrow:horizontal {\n"
"    border: 2px solid #B0B0B0; /* Dark grey color */\n"
"    width: 3px;\n"
"    height: 3px;\n"
"    background: #FFFFFF; /* White arrow background */\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"")
        self.bg = QtWidgets.QWidget(MainWindow)
        self.bg.setObjectName("bg")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.bg)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topBar = QtWidgets.QFrame(self.bg)
        self.topBar.setMaximumSize(QtCore.QSize(16777215, 60))
        self.topBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topBar.setObjectName("topBar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topBar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logoTextFrame = QtWidgets.QFrame(self.topBar)
        self.logoTextFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logoTextFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logoTextFrame.setObjectName("logoTextFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.logoTextFrame)
        self.verticalLayout_2.setContentsMargins(30, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblTxtLogo = QtWidgets.QLabel(self.logoTextFrame)
        self.lblTxtLogo.setStyleSheet("\n"
"color:#D9DAE6;\n"
"font: 81 12pt \"Rubik\";\n"
"")
        self.lblTxtLogo.setObjectName("lblTxtLogo")
        self.verticalLayout_2.addWidget(self.lblTxtLogo)
        self.horizontalLayout.addWidget(self.logoTextFrame)
        self.topBarButtons = QtWidgets.QFrame(self.topBar)
        self.topBarButtons.setStyleSheet("QPushButton {\n"
"background:transparent;\n"
"border:2px solid #8F919A;\n"
"border-radius:5px;\n"
"}")
        self.topBarButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topBarButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topBarButtons.setObjectName("topBarButtons")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.topBarButtons)
        self.horizontalLayout_2.setContentsMargins(0, 0, 40, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minimizeAppBtn = QtWidgets.QPushButton(self.topBarButtons)
        self.minimizeAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.minimizeAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.minimizeAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimizeAppBtn.setStyleSheet("")
        self.minimizeAppBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/icons/icon_minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeAppBtn.setIcon(icon)
        self.minimizeAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.minimizeAppBtn.setObjectName("minimizeAppBtn")
        self.horizontalLayout_2.addWidget(self.minimizeAppBtn)
        self.maximizeRestoreAppBtn = QtWidgets.QPushButton(self.topBarButtons)
        self.maximizeRestoreAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.maximizeRestoreAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.maximizeRestoreAppBtn.setFont(font)
        self.maximizeRestoreAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.maximizeRestoreAppBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/icons/icon_restore.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maximizeRestoreAppBtn.setIcon(icon1)
        self.maximizeRestoreAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.maximizeRestoreAppBtn.setObjectName("maximizeRestoreAppBtn")
        self.horizontalLayout_2.addWidget(self.maximizeRestoreAppBtn)
        self.closeAppBtn = QtWidgets.QPushButton(self.topBarButtons)
        self.closeAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.closeAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.closeAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeAppBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/icons/icon_close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeAppBtn.setIcon(icon2)
        self.closeAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.closeAppBtn.setObjectName("closeAppBtn")
        self.horizontalLayout_2.addWidget(self.closeAppBtn)
        self.horizontalLayout.addWidget(self.topBarButtons, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.topBar)
        self.mainBar = QtWidgets.QFrame(self.bg)
        self.mainBar.setStyleSheet("")
        self.mainBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainBar.setObjectName("mainBar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.mainBar)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.leftBar = QtWidgets.QFrame(self.mainBar)
        self.leftBar.setMinimumSize(QtCore.QSize(130, 0))
        self.leftBar.setStyleSheet("QLabel {\n"
"color:#8588A1;\n"
"}\n"
"/* General button style */\n"
"QPushButton {\n"
"    width: 200px;\n"
"    height: 28px;\n"
"    border-radius: 5px;\n"
"    font-size: 16px;\n"
"    text-align: center;\n"
"    margin: 10px 0;\n"
"    display: block;\n"
"    padding: 5px;\n"
"    font-family: Rubik, sans-serif;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"/* Session Button: Green Outline */\n"
"#btnSmt8Ready {\n"
"    border: 2px solid #28a745;  /* Green border */\n"
"    background-color: transparent;\n"
"    color: #28a745;  /* Green text */\n"
"}\n"
"/*\n"
"#btnSmt8Ready:hover {\n"
"    background-color: #28a745;\n"
"    color: #fff;\n"
"}\n"
"\n"
"/* Host Controller Button: Green Background */\n"
"#btnHostController {\n"
"    border: 2px solid #28a745;  /* Green border */\n"
"    background-color: transparent;\n"
"    color: #28a745;  /* White text */\n"
"}\n"
"/*\n"
"#btnHostController:hover {\n"
"background-color: #218838;\n"
"color:#fff;\n"
"}\n"
"\n"
"/* ACS Edge Button: Orange Outline */\n"
"#btnAcsEdge {\n"
"    border: 2px solid #fd7e14;  /* Orange border */\n"
"    background-color: transparent;\n"
"    color: #fd7e14;  /* Orange text */\n"
"}\n"
"/*\n"
"#btnAcsEdge:hover {\n"
"    background-color: #fd7e14;\n"
"    color: #fff;\n"
"}\n"
"\n"
"/* Test Floor Server Button: Gray Outline */\n"
"#btnTestFloorServer {\n"
"    border: 2px solid #6c757d;  /* Gray border */\n"
"    background-color: transparent;\n"
"    color: #6c757d;  /* Gray text */\n"
"}\n"
"/*\n"
"#btnTestFloorServer:hover {\n"
"    background-color: #6c757d;\n"
"    color: #fff;\n"
"}\n"
"\n"
"\n"
"")
        self.leftBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftBar.setObjectName("leftBar")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.leftBar)
        self.verticalLayout_3.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_8 = QtWidgets.QFrame(self.leftBar)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_15.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.lblLogo = QtWidgets.QLabel(self.frame_8)
        self.lblLogo.setText("")
        self.lblLogo.setPixmap(QtGui.QPixmap(":/icons/images/icons/logo.png"))
        self.lblLogo.setScaledContents(True)
        self.lblLogo.setObjectName("lblLogo")
        self.verticalLayout_15.addWidget(self.lblLogo)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.frame_7 = QtWidgets.QFrame(self.leftBar)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.frame_7)
        self.label.setStyleSheet("color:#9A0143;\n"
"")
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.btnSmt8Ready = QtWidgets.QPushButton(self.frame_7)
        self.btnSmt8Ready.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnSmt8Ready.setObjectName("btnSmt8Ready")
        self.verticalLayout_6.addWidget(self.btnSmt8Ready)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem)
        self.frame_14 = QtWidgets.QFrame(self.frame_7)
        self.frame_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_6.addWidget(self.frame_14)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.frame_3 = QtWidgets.QFrame(self.leftBar)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_10 = QtWidgets.QFrame(self.frame_3)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.frame_10)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.label_3)
        self.btnHostController = QtWidgets.QPushButton(self.frame_10)
        self.btnHostController.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnHostController.setObjectName("btnHostController")
        self.verticalLayout_9.addWidget(self.btnHostController)
        self.verticalLayout_12.addWidget(self.frame_10)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.leftBar)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_13.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_11 = QtWidgets.QFrame(self.frame_4)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.frame_11)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_10.addWidget(self.label_4)
        self.btnAcsEdge = QtWidgets.QPushButton(self.frame_11)
        self.btnAcsEdge.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnAcsEdge.setObjectName("btnAcsEdge")
        self.verticalLayout_10.addWidget(self.btnAcsEdge)
        self.verticalLayout_13.addWidget(self.frame_11)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_6 = QtWidgets.QFrame(self.leftBar)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_13 = QtWidgets.QFrame(self.frame_6)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_5 = QtWidgets.QLabel(self.frame_13)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_11.addWidget(self.label_5)
        self.btnTestFloorServer = QtWidgets.QPushButton(self.frame_13)
        self.btnTestFloorServer.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnTestFloorServer.setObjectName("btnTestFloorServer")
        self.verticalLayout_11.addWidget(self.btnTestFloorServer)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_11.addItem(spacerItem1)
        self.frame_15 = QtWidgets.QFrame(self.frame_13)
        self.frame_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_11.addWidget(self.frame_15)
        self.verticalLayout_14.addWidget(self.frame_13)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(self.leftBar)
        self.frame_5.setStyleSheet("#lblAdvancedControl {\n"
"    max-width: 15px;  /* Diameter of the circle */\n"
"    max-height: 15px;\n"
"    border-radius: 7px;  /* Makes it a circle */\n"
"    display: inline-block;  /* Inline element for placing next to text */\n"
"    margin-right: 10px;  /* Space between circle and text */\n"
"    background-color:green;\n"
"}\n"
"#lblDataCollection {\n"
"    max-width: 15px;  /* Diameter of the circle */\n"
"    max-height: 15px;\n"
"    border-radius: 7px;  /* Makes it a circle */\n"
"    display: inline-block;  /* Inline element for placing next to text */\n"
"    margin-right: 10px;  /* Space between circle and text */\n"
"    background-color:red;\n"
"}\n"
"#lblBasicControl {\n"
"   max-width: 15px;  /* Diameter of the circle */\n"
"    max-height: 15px;\n"
"    border-radius: 7px;  /* Makes it a circle */\n"
"    display: inline-block;  /* Inline element for placing next to text */\n"
"    margin-right: 10px;  /* Space between circle and text */\n"
"    background-color:green;\n"
"}\n"
"QLabel {\n"
"font: 9pt \"Rubik\";\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setObjectName("gridLayout")
        self.lblAdvancedControl = QtWidgets.QLabel(self.frame_5)
        self.lblAdvancedControl.setStyleSheet("")
        self.lblAdvancedControl.setText("")
        self.lblAdvancedControl.setObjectName("lblAdvancedControl")
        self.gridLayout.addWidget(self.lblAdvancedControl, 0, 0, 1, 1)
        self.lblBasicControlText = QtWidgets.QLabel(self.frame_5)
        self.lblBasicControlText.setObjectName("lblBasicControlText")
        self.gridLayout.addWidget(self.lblBasicControlText, 2, 1, 1, 1)
        self.lblDataCollection = QtWidgets.QLabel(self.frame_5)
        self.lblDataCollection.setText("")
        self.lblDataCollection.setObjectName("lblDataCollection")
        self.gridLayout.addWidget(self.lblDataCollection, 1, 0, 1, 1)
        self.lblDataCollectiobText = QtWidgets.QLabel(self.frame_5)
        self.lblDataCollectiobText.setObjectName("lblDataCollectiobText")
        self.gridLayout.addWidget(self.lblDataCollectiobText, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 1, 1, 1)
        self.lblBasicControl = QtWidgets.QLabel(self.frame_5)
        self.lblBasicControl.setText("")
        self.lblBasicControl.setObjectName("lblBasicControl")
        self.gridLayout.addWidget(self.lblBasicControl, 2, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.horizontalLayout_3.addWidget(self.leftBar)
        self.frame_2 = QtWidgets.QFrame(self.mainBar)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(0, 30, 0, 30)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mainTableFrame = QtWidgets.QFrame(self.frame_2)
        self.mainTableFrame.setStyleSheet("background-color:white;")
        self.mainTableFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainTableFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainTableFrame.setObjectName("mainTableFrame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.mainTableFrame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.TableFrame = QtWidgets.QFrame(self.mainTableFrame)
        self.TableFrame.setStyleSheet("background-color:white;")
        self.TableFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TableFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TableFrame.setObjectName("TableFrame")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.TableFrame)
        self.verticalLayout_17.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.OuterFrame = QtWidgets.QFrame(self.TableFrame)
        self.OuterFrame.setStyleSheet("background-color:white;")
        self.OuterFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.OuterFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.OuterFrame.setObjectName("OuterFrame")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.OuterFrame)
        self.verticalLayout_18.setContentsMargins(0, 6, 0, -1)
        self.verticalLayout_18.setSpacing(8)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.scrollArea = QtWidgets.QScrollArea(self.OuterFrame)
        self.scrollArea.setStyleSheet("\n"
"\n"
"QLabel {\n"
"    color:#667085;\n"
"    font: 57 8.5pt \"Rubik Medium\";\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: #667085;\n"
"    font: 87 10pt \"Rubik Medium\";\n"
"\n"
"}\n"
"\n"
"")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 676, 812))
        self.scrollAreaWidgetContents.setStyleSheet("    background-color: #FFFFFF; /* Set background to white */\n"
"")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_79 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_79.setContentsMargins(0, -1, 0, 11)
        self.verticalLayout_79.setObjectName("verticalLayout_79")
        self.frame_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_9.setStyleSheet("#frame_9\n"
"{\n"
"border-bottom: 1px solid #E4E7EC;\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_8.setContentsMargins(-1, -1, 30, -1)
        self.horizontalLayout_8.setSpacing(20)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btnWarning = QtWidgets.QPushButton(self.frame_9)
        self.btnWarning.setMinimumSize(QtCore.QSize(0, 38))
        self.btnWarning.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnWarning.setStyleSheet("color:#A0104E;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/icons/warning.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnWarning.setIcon(icon3)
        self.btnWarning.setIconSize(QtCore.QSize(25, 25))
        self.btnWarning.setFlat(True)
        self.btnWarning.setObjectName("btnWarning")
        self.horizontalLayout_8.addWidget(self.btnWarning)
        self.lblDateTime = QtWidgets.QLabel(self.frame_9)
        self.lblDateTime.setStyleSheet("")
        self.lblDateTime.setObjectName("lblDateTime")
        self.horizontalLayout_8.addWidget(self.lblDateTime)
        self.lblLink = QtWidgets.QLabel(self.frame_9)
        self.lblLink.setStyleSheet("")
        self.lblLink.setWordWrap(True)
        self.lblLink.setObjectName("lblLink")
        self.horizontalLayout_8.addWidget(self.lblLink)
        self.verticalLayout_79.addWidget(self.frame_9)
        self.frame_28 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_28.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_28.setStyleSheet("#frame_28\n"
"{\n"
"border-bottom: 1px solid #E4E7EC;\n"
"}")
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_28)
        self.horizontalLayout_20.setContentsMargins(-1, -1, 30, -1)
        self.horizontalLayout_20.setSpacing(20)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.btnWarning_12 = QtWidgets.QPushButton(self.frame_28)
        self.btnWarning_12.setMinimumSize(QtCore.QSize(0, 38))
        self.btnWarning_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnWarning_12.setStyleSheet("color:#A0104E;")
        self.btnWarning_12.setIcon(icon3)
        self.btnWarning_12.setIconSize(QtCore.QSize(25, 25))
        self.btnWarning_12.setFlat(True)
        self.btnWarning_12.setObjectName("btnWarning_12")
        self.horizontalLayout_20.addWidget(self.btnWarning_12)
        self.lblDateTime_12 = QtWidgets.QLabel(self.frame_28)
        self.lblDateTime_12.setStyleSheet("")
        self.lblDateTime_12.setObjectName("lblDateTime_12")
        self.horizontalLayout_20.addWidget(self.lblDateTime_12)
        self.lblLink_12 = QtWidgets.QLabel(self.frame_28)
        self.lblLink_12.setStyleSheet("")
        self.lblLink_12.setWordWrap(True)
        self.lblLink_12.setObjectName("lblLink_12")
        self.horizontalLayout_20.addWidget(self.lblLink_12)
        self.verticalLayout_79.addWidget(self.frame_28)
        self.frame_27 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_27.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_27.setStyleSheet("#frame_27\n"
"{\n"
"border-bottom: 1px solid #E4E7EC;\n"
"}")
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_27)
        self.horizontalLayout_19.setContentsMargins(-1, -1, 30, -1)
        self.horizontalLayout_19.setSpacing(20)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.btnWarning_11 = QtWidgets.QPushButton(self.frame_27)
        self.btnWarning_11.setMinimumSize(QtCore.QSize(0, 38))
        self.btnWarning_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnWarning_11.setStyleSheet("color:#A0104E;")
        self.btnWarning_11.setIcon(icon3)
        self.btnWarning_11.setIconSize(QtCore.QSize(25, 25))
        self.btnWarning_11.setFlat(True)
        self.btnWarning_11.setObjectName("btnWarning_11")
        self.horizontalLayout_19.addWidget(self.btnWarning_11)
        self.lblDateTime_11 = QtWidgets.QLabel(self.frame_27)
        self.lblDateTime_11.setStyleSheet("")
        self.lblDateTime_11.setObjectName("lblDateTime_11")
        self.horizontalLayout_19.addWidget(self.lblDateTime_11)
        self.lblLink_11 = QtWidgets.QLabel(self.frame_27)
        self.lblLink_11.setStyleSheet("")
        self.lblLink_11.setWordWrap(True)
        self.lblLink_11.setObjectName("lblLink_11")
        self.horizontalLayout_19.addWidget(self.lblLink_11)
        self.verticalLayout_79.addWidget(self.frame_27)
        self.frame_18 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_18.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_18.setStyleSheet("#frame_18\n"
"{\n"
"border-bottom: 1px solid #E4E7EC;\n"
"    font-family: Rubik, sans-serif;\n"
"\n"
"}")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_10.setContentsMargins(-1, -1, 30, -1)
        self.horizontalLayout_10.setSpacing(20)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btnWarning_2 = QtWidgets.QPushButton(self.frame_18)
        self.btnWarning_2.setMinimumSize(QtCore.QSize(0, 38))
        self.btnWarning_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnWarning_2.setStyleSheet("color:#A0104E;")
        self.btnWarning_2.setIcon(icon3)
        self.btnWarning_2.setIconSize(QtCore.QSize(25, 25))
        self.btnWarning_2.setFlat(True)
        self.btnWarning_2.setObjectName("btnWarning_2")
        self.horizontalLayout_10.addWidget(self.btnWarning_2)
        self.lblDateTime_2 = QtWidgets.QLabel(self.frame_18)
        self.lblDateTime_2.setStyleSheet("")
        self.lblDateTime_2.setObjectName("lblDateTime_2")
        self.horizontalLayout_10.addWidget(self.lblDateTime_2)
        self.lblLink_2 = QtWidgets.QLabel(self.frame_18)
        self.lblLink_2.setStyleSheet("")
        self.lblLink_2.setWordWrap(True)
        self.lblLink_2.setObjectName("lblLink_2")
        self.horizontalLayout_10.addWidget(self.lblLink_2)
        self.verticalLayout_79.addWidget(self.frame_18)
        self.frame_26 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_26.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_26.setStyleSheet("#frame_26\n"
"{\n"
"border-bottom: 1px solid #E4E7EC;\n"
"}")
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_18.setContentsMargins(-1, -1, 30, -1)
        self.horizontalLayout_18.setSpacing(20)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.btnWarning_10 = QtWidgets.QPushButton(self.frame_26)
        self.btnWarning_10.setMinimumSize(QtCore.QSize(0, 38))
        self.btnWarning_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnWarning_10.setStyleSheet("color:#A0104E;")
        self.btnWarning_10.setIcon(icon3)
        self.btnWarning_10.setIconSize(QtCore.QSize(25, 25))
        self.btnWarning_10.setFlat(True)
        self.btnWarning_10.setObjectName("btnWarning_10")
        self.horizontalLayout_18.addWidget(self.btnWarning_10)
        self.lblDateTime_10 = QtWidgets.QLabel(self.frame_26)
        self.lblDateTime_10.setStyleSheet("")
        self.lblDateTime_10.setObjectName("lblDateTime_10")
        self.horizontalLayout_18.addWidget(self.lblDateTime_10)
        self.lblLink_10 = QtWidgets.QLabel(self.frame_26)
        self.lblLink_10.setStyleSheet("")
        self.lblLink_10.setWordWrap(True)
        self.lblLink_10.setObjectName("lblLink_10")
        self.horizontalLayout_18.addWidget(self.lblLink_10)
        self.verticalLayout_79.addWidget(self.frame_26)
        self.frame_19 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_19.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_19.setStyleSheet("#frame_19\n"
"{\n"
"border-bottom: 1px solid #E4E7EC;\n"
"}")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_11.setContentsMargins(-1, -1, 30, -1)
        self.horizontalLayout_11.setSpacing(20)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.btnWarning_3 = QtWidgets.QPushButton(self.frame_19)
        self.btnWarning_3.setMinimumSize(QtCore.QSize(0, 38))
        self.btnWarning_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnWarning_3.setStyleSheet("color:#A0104E;")
        self.btnWarning_3.setIcon(icon3)
        self.btnWarning_3.setIconSize(QtCore.QSize(25, 25))
        self.btnWarning_3.setFlat(True)
        self.btnWarning_3.setObjectName("btnWarning_3")
        self.horizontalLayout_11.addWidget(self.btnWarning_3)
        self.lblDateTime_3 = QtWidgets.QLabel(self.frame_19)
        self.lblDateTime_3.setStyleSheet("")
        self.lblDateTime_3.setObjectName("lblDateTime_3")
        self.horizontalLayout_11.addWidget(self.lblDateTime_3)
        self.lblLink_3 = QtWidgets.QLabel(self.frame_19)
        self.lblLink_3.setStyleSheet("")
        self.lblLink_3.setWordWrap(True)
        self.lblLink_3.setObjectName("lblLink_3")
        self.horizontalLayout_11.addWidget(self.lblLink_3)
        self.verticalLayout_79.addWidget(self.frame_19)
        self.frame_20 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_20.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_20.setStyleSheet("#frame_20\n"
"{\n"
"border-bottom: 1px solid #E4E7EC;\n"
"}")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_12.setContentsMargins(-1, -1, 30, -1)
        self.horizontalLayout_12.setSpacing(20)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.btnWarning_4 = QtWidgets.QPushButton(self.frame_20)
        self.btnWarning_4.setMinimumSize(QtCore.QSize(0, 38))
        self.btnWarning_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnWarning_4.setStyleSheet("color:#A0104E;")
        self.btnWarning_4.setIcon(icon3)
        self.btnWarning_4.setIconSize(QtCore.QSize(25, 25))
        self.btnWarning_4.setFlat(True)
        self.btnWarning_4.setObjectName("btnWarning_4")
        self.horizontalLayout_12.addWidget(self.btnWarning_4)
        self.lblDateTime_4 = QtWidgets.QLabel(self.frame_20)
        self.lblDateTime_4.setStyleSheet("")
        self.lblDateTime_4.setObjectName("lblDateTime_4")
        self.horizontalLayout_12.addWidget(self.lblDateTime_4)
        self.lblLink_4 = QtWidgets.QLabel(self.frame_20)
        self.lblLink_4.setStyleSheet("")
        self.lblLink_4.setWordWrap(True)
        self.lblLink_4.setObjectName("lblLink_4")
        self.horizontalLayout_12.addWidget(self.lblLink_4)
        self.verticalLayout_79.addWidget(self.frame_20)
        self.frame_21 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_21.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_21.setStyleSheet("#frame_21\n"
"{\n"
"border-bottom: 1px solid #E4E7EC;\n"
"}")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_13.setContentsMargins(-1, -1, 30, -1)
        self.horizontalLayout_13.setSpacing(20)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.btnWarning_5 = QtWidgets.QPushButton(self.frame_21)
        self.btnWarning_5.setMinimumSize(QtCore.QSize(0, 38))
        self.btnWarning_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnWarning_5.setStyleSheet("color:#A0104E;")
        self.btnWarning_5.setIcon(icon3)
        self.btnWarning_5.setIconSize(QtCore.QSize(25, 25))
        self.btnWarning_5.setFlat(True)
        self.btnWarning_5.setObjectName("btnWarning_5")
        self.horizontalLayout_13.addWidget(self.btnWarning_5)
        self.lblDateTime_5 = QtWidgets.QLabel(self.frame_21)
        self.lblDateTime_5.setStyleSheet("")
        self.lblDateTime_5.setObjectName("lblDateTime_5")
        self.horizontalLayout_13.addWidget(self.lblDateTime_5)
        self.lblLink_5 = QtWidgets.QLabel(self.frame_21)
        self.lblLink_5.setStyleSheet("")
        self.lblLink_5.setWordWrap(True)
        self.lblLink_5.setObjectName("lblLink_5")
        self.horizontalLayout_13.addWidget(self.lblLink_5)
        self.verticalLayout_79.addWidget(self.frame_21)
        self.frame_22 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_22.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_22.setStyleSheet("#frame_22\n"
"{\n"
"border-bottom: 1px solid #E4E7EC;\n"
"}")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_14.setContentsMargins(-1, -1, 30, -1)
        self.horizontalLayout_14.setSpacing(20)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.btnWarning_6 = QtWidgets.QPushButton(self.frame_22)
        self.btnWarning_6.setMinimumSize(QtCore.QSize(0, 38))
        self.btnWarning_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnWarning_6.setStyleSheet("color:#A0104E;")
        self.btnWarning_6.setIcon(icon3)
        self.btnWarning_6.setIconSize(QtCore.QSize(25, 25))
        self.btnWarning_6.setFlat(True)
        self.btnWarning_6.setObjectName("btnWarning_6")
        self.horizontalLayout_14.addWidget(self.btnWarning_6)
        self.lblDateTime_6 = QtWidgets.QLabel(self.frame_22)
        self.lblDateTime_6.setStyleSheet("background-color:transparent;\n"
"font: BOLD 10pt \"Bell MT\";\n"
"color:#667085;")
        self.lblDateTime_6.setObjectName("lblDateTime_6")
        self.horizontalLayout_14.addWidget(self.lblDateTime_6)
        self.lblLink_6 = QtWidgets.QLabel(self.frame_22)
        self.lblLink_6.setStyleSheet("")
        self.lblLink_6.setWordWrap(True)
        self.lblLink_6.setObjectName("lblLink_6")
        self.horizontalLayout_14.addWidget(self.lblLink_6)
        self.verticalLayout_79.addWidget(self.frame_22)
        self.frame_23 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_23.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_23.setStyleSheet("#frame_23\n"
"{\n"
"border-bottom: 1px solid #E4E7EC;\n"
"}")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_15.setContentsMargins(-1, -1, 30, -1)
        self.horizontalLayout_15.setSpacing(20)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.btnWarning_7 = QtWidgets.QPushButton(self.frame_23)
        self.btnWarning_7.setMinimumSize(QtCore.QSize(0, 38))
        self.btnWarning_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnWarning_7.setStyleSheet("color:#A0104E;")
        self.btnWarning_7.setIcon(icon3)
        self.btnWarning_7.setIconSize(QtCore.QSize(25, 25))
        self.btnWarning_7.setFlat(True)
        self.btnWarning_7.setObjectName("btnWarning_7")
        self.horizontalLayout_15.addWidget(self.btnWarning_7)
        self.lblDateTime_7 = QtWidgets.QLabel(self.frame_23)
        self.lblDateTime_7.setStyleSheet("")
        self.lblDateTime_7.setObjectName("lblDateTime_7")
        self.horizontalLayout_15.addWidget(self.lblDateTime_7)
        self.lblLink_7 = QtWidgets.QLabel(self.frame_23)
        self.lblLink_7.setStyleSheet("")
        self.lblLink_7.setWordWrap(True)
        self.lblLink_7.setObjectName("lblLink_7")
        self.horizontalLayout_15.addWidget(self.lblLink_7)
        self.verticalLayout_79.addWidget(self.frame_23)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_79.addItem(spacerItem2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_18.addWidget(self.scrollArea)
        self.verticalLayout_17.addWidget(self.OuterFrame)
        self.verticalLayout_8.addWidget(self.TableFrame)
        self.verticalLayout_4.addWidget(self.mainTableFrame)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.mainBar)
        self.frame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setContentsMargins(0, 30, 20, 30)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.rightMainFrame = QtWidgets.QFrame(self.frame)
        self.rightMainFrame.setMinimumSize(QtCore.QSize(280, 0))
        self.rightMainFrame.setStyleSheet("")
        self.rightMainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightMainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightMainFrame.setObjectName("rightMainFrame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.rightMainFrame)
        self.verticalLayout_7.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.OuterFrameRight = QtWidgets.QFrame(self.rightMainFrame)
        self.OuterFrameRight.setStyleSheet("background-color:white;")
        self.OuterFrameRight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.OuterFrameRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.OuterFrameRight.setObjectName("OuterFrameRight")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.OuterFrameRight)
        self.verticalLayout_20.setContentsMargins(0, 6, 0, -1)
        self.verticalLayout_20.setSpacing(8)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.frame_16 = QtWidgets.QFrame(self.OuterFrameRight)
        self.frame_16.setStyleSheet("")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_4.setContentsMargins(5, -1, 11, -1)
        self.horizontalLayout_4.setSpacing(15)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cmbxContainer = QtWidgets.QComboBox(self.frame_16)
        self.cmbxContainer.setStyleSheet("")
        self.cmbxContainer.setObjectName("cmbxContainer")
        self.cmbxContainer.addItem("")
        self.horizontalLayout_4.addWidget(self.cmbxContainer)
        self.cmbxStatus = QtWidgets.QComboBox(self.frame_16)
        self.cmbxStatus.setObjectName("cmbxStatus")
        self.cmbxStatus.addItem("")
        self.horizontalLayout_4.addWidget(self.cmbxStatus)
        self.verticalLayout_20.addWidget(self.frame_16)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.OuterFrameRight)
        self.scrollArea_2.setStyleSheet("\n"
"\n"
"QLabel {\n"
"    color:#667085;\n"
"font: 57 8.5pt \"Rubik Medium\";\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton {\n"
"    font: BOLD 10pt \"Arial\";\n"
"    color: #667085;\n"
"}\n"
"\n"
"")
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrollArea_2.setLineWidth(1)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 264, 659))
        self.scrollAreaWidgetContents_2.setStyleSheet("    background-color: #FFFFFF; /* Set background to white */\n"
"")
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_80 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_80.setContentsMargins(0, -1, 0, 11)
        self.verticalLayout_80.setObjectName("verticalLayout_80")
        self.frame_12 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_12.setStyleSheet("#frame_12\n"
"{\n"
"border-bottom: 1px solid #E4E7EC;\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_9.setContentsMargins(5, -1, 11, -1)
        self.horizontalLayout_9.setSpacing(15)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lblContainer = QtWidgets.QLabel(self.frame_12)
        self.lblContainer.setStyleSheet("")
        self.lblContainer.setObjectName("lblContainer")
        self.horizontalLayout_9.addWidget(self.lblContainer)
        self.frame_17 = QtWidgets.QFrame(self.frame_12)
        self.frame_17.setStyleSheet("")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblStatusRec = QtWidgets.QLabel(self.frame_17)
        self.lblStatusRec.setMinimumSize(QtCore.QSize(25, 15))
        self.lblStatusRec.setStyleSheet("    max-width: 15px;\n"
"    max-height: 15px;\n"
"    border-radius: 7px; \n"
"    margin-right: 10px; \n"
"    background-color: #25993F;")
        self.lblStatusRec.setText("")
        self.lblStatusRec.setObjectName("lblStatusRec")
        self.horizontalLayout_5.addWidget(self.lblStatusRec)
        self.label_8 = QtWidgets.QLabel(self.frame_17)
        self.label_8.setStyleSheet("color:#25993F;")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.horizontalLayout_9.addWidget(self.frame_17)
        self.verticalLayout_80.addWidget(self.frame_12)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_80.addItem(spacerItem3)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_20.addWidget(self.scrollArea_2)
        self.verticalLayout_7.addWidget(self.OuterFrameRight)
        self.verticalLayout_5.addWidget(self.rightMainFrame)
        self.horizontalLayout_3.addWidget(self.frame)
        self.verticalLayout.addWidget(self.mainBar)
        MainWindow.setCentralWidget(self.bg)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblTxtLogo.setText(_translate("MainWindow", "Lorem Ipsum"))
        self.minimizeAppBtn.setToolTip(_translate("MainWindow", "Minimize"))
        self.maximizeRestoreAppBtn.setToolTip(_translate("MainWindow", "Maximize"))
        self.closeAppBtn.setToolTip(_translate("MainWindow", "Close"))
        self.label.setText(_translate("MainWindow", "SESSION"))
        self.btnSmt8Ready.setText(_translate("MainWindow", "SMT8 READY"))
        self.label_3.setText(_translate("MainWindow", "HOST CONTROLLER"))
        self.btnHostController.setText(_translate("MainWindow", "ABLED"))
        self.label_4.setText(_translate("MainWindow", "ACS EDGE"))
        self.btnAcsEdge.setText(_translate("MainWindow", "DISCONNECTED"))
        self.label_5.setText(_translate("MainWindow", "TEST FLOOR SERVER"))
        self.btnTestFloorServer.setText(_translate("MainWindow", "DISABLED"))
        self.lblAdvancedControl.setToolTip(_translate("MainWindow", "The container is currently running and operational."))
        self.lblBasicControlText.setToolTip(_translate("MainWindow", "The container is currently running and operational."))
        self.lblBasicControlText.setText(_translate("MainWindow", "Basic Control"))
        self.lblDataCollection.setToolTip(_translate("MainWindow", "The container has stopped functioning and is not operational."))
        self.lblDataCollectiobText.setToolTip(_translate("MainWindow", "The container has stopped functioning and is not operational."))
        self.lblDataCollectiobText.setText(_translate("MainWindow", "Data Collection"))
        self.label_7.setToolTip(_translate("MainWindow", "The container is currently running and operational."))
        self.label_7.setText(_translate("MainWindow", "Advanced Control"))
        self.lblBasicControl.setToolTip(_translate("MainWindow", "The container is currently running and operational."))
        self.btnWarning.setText(_translate("MainWindow", "   WARNING"))
        self.lblDateTime.setText(_translate("MainWindow", "2024-09-01 - 08:15:20"))
        self.lblLink.setText(_translate("MainWindow", "Failed to load config file:/opt/acs/nexus/cont/app_discriptor.json"))
        self.btnWarning_12.setText(_translate("MainWindow", "   WARNING"))
        self.lblDateTime_12.setText(_translate("MainWindow", "2024-09-01 - 08:15:20"))
        self.lblLink_12.setText(_translate("MainWindow", "Failed to load config file:/opt/acs/nexus/cont/app_discriptor.json"))
        self.btnWarning_11.setText(_translate("MainWindow", "   WARNING"))
        self.lblDateTime_11.setText(_translate("MainWindow", "2024-09-01 - 08:15:20"))
        self.lblLink_11.setText(_translate("MainWindow", "Failed to load config file:/opt/acs/nexus/cont/app_discriptor.json"))
        self.btnWarning_2.setText(_translate("MainWindow", "   WARNING"))
        self.lblDateTime_2.setText(_translate("MainWindow", "2024-09-01 - 08:15:20"))
        self.lblLink_2.setText(_translate("MainWindow", "Failed to load config file:/opt/acs/nexus/cont/app_discriptor.json"))
        self.btnWarning_10.setText(_translate("MainWindow", "   WARNING"))
        self.lblDateTime_10.setText(_translate("MainWindow", "2024-09-01 - 08:15:20"))
        self.lblLink_10.setText(_translate("MainWindow", "Failed to load config file:/opt/acs/nexus/cont/app_discriptor.json"))
        self.btnWarning_3.setText(_translate("MainWindow", "   WARNING"))
        self.lblDateTime_3.setText(_translate("MainWindow", "2024-09-01 - 08:15:20"))
        self.lblLink_3.setText(_translate("MainWindow", "Failed to load config file:/opt/acs/nexus/cont/app_discriptor.json"))
        self.btnWarning_4.setText(_translate("MainWindow", "   WARNING"))
        self.lblDateTime_4.setText(_translate("MainWindow", "2024-09-01 - 08:15:20"))
        self.lblLink_4.setText(_translate("MainWindow", "Failed to load config file:/opt/acs/nexus/cont/app_discriptor.json"))
        self.btnWarning_5.setText(_translate("MainWindow", "   WARNING"))
        self.lblDateTime_5.setText(_translate("MainWindow", "2024-09-01 - 08:15:20"))
        self.lblLink_5.setText(_translate("MainWindow", "Failed to load config file:/opt/acs/nexus/cont/app_discriptor.json"))
        self.btnWarning_6.setText(_translate("MainWindow", "   WARNING"))
        self.lblDateTime_6.setText(_translate("MainWindow", "2024-09-01 - 08:15:20"))
        self.lblLink_6.setText(_translate("MainWindow", "Failed to load config file:/opt/acs/nexus/cont/app_discriptor.json"))
        self.btnWarning_7.setText(_translate("MainWindow", "   WARNING"))
        self.lblDateTime_7.setText(_translate("MainWindow", "2024-09-01 - 08:15:20"))
        self.lblLink_7.setText(_translate("MainWindow", "Failed to load config file:/opt/acs/nexus/cont/app_discriptor.json"))
        self.cmbxContainer.setItemText(0, _translate("MainWindow", "CONTAINER"))
        self.cmbxStatus.setItemText(0, _translate("MainWindow", "STATUS"))
        self.lblContainer.setText(_translate("MainWindow", "KafkaBroker"))
        self.label_8.setText(_translate("MainWindow", "running"))
import resources_rc
